### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by ChillChii** [Dew3/Roblox-Username-Checker#1]
I just wanna check usernames but I have no idea how to even open this

**Comment by Dew3** [comment]
To use my Roblox name checker you have to have python 3.9.0 installed on your computer. I recommend using cloning my project through terminal (Heres a link that explains it well: https://www.youtube.com/watch?v=ttB0-Vz7Ho0); If that doesn't make any sense follow these next steps after downloading Python: Download a text editor such as sublime text. With sublime text you can make a new python program where you can copy and paste in my code that is on my github. Save it as Main.py file and then go to your terminal. Here is a link that displays how to navigate a Mac terminal: https://www.youtube.com/watch?v=j6vKLJxAKfw. While in the same directory that the .py file is that you just made with my code, you can type python3 Main.py and it will make a Usernames and Available .txt files in your directory. Enter in the names you want to check then rerun the program from the terminal. If any of these words sound foreign just google them and you will be on your way!

**Comment by ChillChii** [comment]
im also on windows
