### ISSUE TITLE
Still need help.

### ISSUE THREAD

**Issue by ChillChii** [Dew3/Roblox-Username-Checker#2]
I tried to follow what you said, then this happened import robloxapi, asyncio
ModuleNotFoundError: No module named 'robloxapi'

im confused is it possible if you could help me on discord while I screenshare or something?

**Comment by Dew3** [comment]
Yeah that will work feel free to join my discord and pm me a message we can go from there(This link will expire in 7 days): https://discord.gg/dfgHEe8G. Apologies for delayed response!
